POST http://localhost:8080/auth/create-user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImNyZWF0ZWRfYXQiOiIyMDI2LTA4LTI5VDE4OjU5OjM5LjUyODU0OFoiLCJkZWxldGVkX2F0IjpudWxsLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjAxYTA0ZWU0LTRiNTAtNzY4Ny1iZWE0LTNhOTM2ZjkzMGRlMCIsIm5hbWUiOiJndWlsaGVyZW0iLCJyb2xlX2lkIjoiMDFhMDQ5MjQtNWQzNC03YjdlLTllNTgtOWNhYjllYzdlMTZlIiwicm9sZV9uYW1lIjoiQWRtaW4iLCJ1cGRhdGVkX2F0IjoiMjAyNi0wOC0yOVQxODo1OTozOS41Mjg1NDhaIn0sImV4cCI6MTc4ODIxODY4MCwiaWF0IjoxNzg4MTg5ODgwfQ.JnsLwldUIqFW0kRT3HNR3AzGYrjvN9mmFWQ7H39Wf3w

{
    "name": "driver",
    "email": "driver@driver.com",
    "password": "123321222",
    "role_id": "01a0586e-8ef4-7c3d-bf9c-48c6ce32cc43"
}