POST http://localhost:8080/auth/create-role HTTP/1.1
content-type: application/json

{
  "name": "admin 2",
  "description": "Administrator role with full access",
  "permissions": [
    {
      "action": "*",
      "path": "*"
    }
  ]
}

# {
#   "id": "01a0181a-4557-760d-8ed9-09dd62e34f63",
#   "name": "admin 2",
#   "description": "Administrator role with full access",
#   "permissions": null
# }
