GET http://localhost:8080/auth/find-all-roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImNyZWF0ZWRfYXQiOiIyMDI2LTA4LTI5VDE4OjU5OjM5LjUyODU0OFoiLCJkZWxldGVkX2F0IjpudWxsLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjAxYTA0ZWU0LTRiNTAtNzY4Ny1iZWE0LTNhOTM2ZjkzMGRlMCIsIm5hbWUiOiJndWlsaGVyZW0iLCJyb2xlX2lkIjoiMDFhMDQ5MjQtNWQzNC03YjdlLTllNTgtOWNhYjllYzdlMTZlIiwicm9sZV9uYW1lIjoiQWRtaW4iLCJ1cGRhdGVkX2F0IjoiMjAyNi0wOC0yOVQxODo1OTozOS41Mjg1NDhaIn0sImV4cCI6MTc4ODE2Mjc5NywiaWF0IjoxNzg4MTMzOTk3fQ.CZqAv0a-a2Q55kMznPUNiA5psEMwG7t4a6wYufGaEf4
