// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"auth/config"
	"auth/internal/application/usecase"
	"auth/internal/infra/repository"
	"auth/internal/infra/service"
	"auth/internal/transport"
	"auth/pkg/authentication"
	"auth/pkg/authorization"
	"github.com/google/wire"
	"github.com/minio/minio-go/v7"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitGRPCAuthTransport(env *config.Env, db *gorm.DB, s3Client *minio.Client) (*transport.AuthTransport, error) {
	userRepositoryInterface := repository.NewUserRepository(db)
	jwt := authentication.NewJWT(env)
	userUsecaseInterface := usecase.NewUserUsecase(userRepositoryInterface, jwt)
	roleRepositoryInterface := repository.NewRoleRepository(db)
	storageServiceInterface := service.NewStorageService(s3Client, env)
	opaSyncServiceInterface := service.NewOPASyncService(roleRepositoryInterface, storageServiceInterface)
	roleUsecaseInterface := usecase.NewRoleUsecase(roleRepositoryInterface, opaSyncServiceInterface)
	opaInterface := authorization.NewOPA(env)
	authTransport := transport.NewAuthTransport(userUsecaseInterface, roleUsecaseInterface, jwt, opaInterface)
	return authTransport, nil
}

// wire.go:

var AuthProviderSet = wire.NewSet(authentication.NewJWT, wire.Bind(new(authentication.TokenValidator), new(*authentication.JWT)), wire.Bind(new(authentication.TokenGenerator), new(*authentication.JWT)))
