syntax = "proto3";

package auth.v1;

option go_package = "proto/gen/auth/v1;authv1";


// Login
message LoginRequest {
string email = 1;
string password = 2;
}

message LoginResponse {
string access_token = 1;
}

// Criar usuario

message CreateUserRequest{
string name = 1;
string email = 2;
string password = 3;
string role_id = 4;
}

message CreateUserResponse{
string name = 1;
string email = 2;
string id = 3;
string role_id = 4;
}

// Deletar usuario

message DeleteUserRequest{
string id = 1;
}

message DeleteUserResponse{
string msg = 1;
}

// Criar cargo

message Permission {
string action = 1; 
string path = 2;   
}

message CreateRoleRequest{
string name = 1;
string description = 2;
repeated Permission permissions = 3; 
}

message CreateRoleResponse{
string id = 1;
string name = 2;
string description = 3;
repeated Permission permissions = 4; 
}

// Deletar cargo

message DeleteRoleRequest{
string id = 1;
}

message DeleteRoleResponse{
string msg = 1;
}

// find user by id
message FindUserByIDRequest{
    string id = 1;
}

message FindUserByIDResponse{
    string name = 1;
    string email = 2;
    string id = 3;
    string role_id = 4;
}


// find role by id
message FindRoleByIDRequest{
    string id = 1;
}

message FindRoleByIDResponse{
    string id = 1;
    string name = 2;
    string description = 3;
    repeated Permission permissions = 4;
}


// find all roles

message Role {
  string id = 1;
  string name = 2;
  string description = 3;
  repeated Permission permissions = 4;
}

message FindAllRolesRequest {}

message FindAllRolesResponse {
  repeated Role roles = 1;
}

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
  rpc CreateRole(CreateRoleRequest) returns (CreateRoleResponse);
  rpc DeleteRole(DeleteRoleRequest) returns (DeleteRoleResponse);
  rpc FindUserByID(FindUserByIDRequest) returns (FindUserByIDResponse);
  rpc FindRoleByID(FindRoleByIDRequest) returns (FindRoleByIDResponse);
  rpc FindAllRoles(FindAllRolesRequest) returns (FindAllRolesResponse);
}