services:
  s3_minio:
    url: http://minio:9000 
    credentials:
      s3_signing:
        environment_credentials: {}

bundles:
  authz_bundle:
    service: s3_minio
    resource: my-bucket/bundle.tar.gz 
    polling:
      min_delay_seconds: 15
      max_delay_seconds: 30

decision_logs:
  console: true