// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"delivery/config"
	"delivery/internal/application/usecase"
	"delivery/internal/infra/repository"
	"delivery/internal/transport"
	"delivery/pkg/authentication"
	"delivery/pkg/authorization"
	"delivery/pkg/grpc_middleware"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"log/slog"
)

// Injectors from wire.go:

func InitDeliveryTransport(env *config.Env, db *mongo.Database, log *slog.Logger) (*transport.DeliveryTransport, error) {
	deliveryRepositoryInterface := repository.NewDeliveryRepository(db, log)
	deliveryUsecaseInterface := usecase.NewDeliveryUsecase(deliveryRepositoryInterface, log)
	opaInterface := authorization.NewOPA(env)
	deliveryTransport := transport.NewDeliveryTransport(deliveryUsecaseInterface, opaInterface, log)
	return deliveryTransport, nil
}

func InitGRPCMiddleware(env *config.Env, log *slog.Logger) (*grpcmiddleware.GRPCMiddleware, error) {
	jwt := authentication.NewJWT(env)
	opaInterface := authorization.NewOPA(env)
	grpcMiddleware := grpcmiddleware.NewGRPCMiddleware(jwt, opaInterface)
	return grpcMiddleware, nil
}

// wire.go:

var JWTProviderSet = wire.NewSet(authentication.NewJWT, wire.Bind(new(authentication.TokenValidator), new(*authentication.JWT)))
